<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{2cd6c072-ca5e-4bc3-9fe1-6217351787c7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_Schrauber();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="131" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>