<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgMAIN" Id="{e6d00dc8-42d8-40ed-9265-2c8ae6cce6a1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgMAIN
VAR
	(* Sonstiges *)
	fbZeitstempel	:	FB_Zeitstempel;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	fbZeitstempel();]]></ST>
    </Implementation>
    <LineIds Name="prgMAIN">
      <LineId Id="8" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>